$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Train model with nyc taxi data

display_name: nyc-taxi-pipeline-example
experiment_name: nyc-taxi-pipeline-example
jobs:

  prep_job:
    type: command
    inputs:
      raw_data: 
          type: uri_folder 
          path: ./data
    outputs:
      prep_data: 
        mode: upload
    code: src/prep
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    compute: azureml:Compute-cluster-VA
    command: >-
      pip install papermill ipykernel &&
      papermill ChurnMensual-AzureML_v2.ipynb
  
